[package]
name = "rollup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
calamine = "0.19.1"
logos = "0.12.1"
petgraph = "0.6.2"
